# Generated by Django 2.2.7 on 2019-11-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caterer',
            fields=[
                ('caterer_id', models.AutoField(primary_key=True, serialize=False)),
                ('caterer_name', models.CharField(default='', max_length=100)),
                ('caterer_phone', models.CharField(default='', max_length=100)),
                ('caterer_email', models.CharField(default='', max_length=100)),
                ('caterer_menu_type', models.CharField(default='', max_length=100)),
                ('caterer_menu_cost_per_person', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(default='', max_length=100)),
                ('customer_last_name', models.CharField(default='', max_length=100)),
                ('customer_street_address', models.CharField(default='', max_length=100)),
                ('customer_city', models.CharField(default='', max_length=100)),
                ('customer_state', models.CharField(default='', max_length=100)),
                ('customer_zip', models.CharField(default='', max_length=5)),
                ('customer_phone', models.CharField(default='', max_length=100)),
                ('customer_email', models.CharField(default='', max_length=100)),
                ('customer_organization', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_room_name', models.CharField(default='', max_length=100)),
                ('venue_rental_fee', models.CharField(default='', max_length=100)),
                ('venue_room_size', models.BigIntegerField()),
                ('venue_room_capacity', models.BigIntegerField()),
                ('is_booked', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('booking_start_time', models.DateTimeField(blank=True, null=True)),
                ('booking_end_time', models.DateTimeField(blank=True, null=True)),
                ('caterer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='capstoneapplication.Caterer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='capstoneapplication.Customer')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='capstoneapplication.Venue')),
            ],
        ),
    ]
